### ISSUE TITLE
Error while creating microgateway app

### ISSUE THREAD

**Issue by ykalidin** [project-flogo/microgateway#35]
The below error is seen while creating the microgateway app:
`flogo create -f flogo.json`

**Error in installing github.com/project-flogo/microgateway@master
Warning: unable to install github.com/project-flogo/microgateway**

While running the generated binary we are getting below error:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6bec03]

goroutine 1 [running]:
github.com/project-flogo/core/app.New(0xc0000a9380, 0x80cb20, 0xc0000d4a00, 0xc0000b40d8, 0x1, 0x1, 0x0, 0x1, 0xc0001bbd40)
	/home/ykalidin/go/pkg/mod/github.com/project-flogo/core@v0.9.0-alpha.5.0.20190227233126-6f35cb28d73f/app/app.go:55 +0x413
github.com/project-flogo/core/engine.New(0xc0000a9380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7f295cd996c0, 0x0)
	/home/ykalidin/go/pkg/mod/github.com/project-flogo/core@v0.9.0-alpha.5.0.20190227233126-6f35cb28d73f/engine/engineimpl.go:113 +0x398
main.main()
	/home/ykalidin/go/src/github.com/project-flogo/microgateway/examples/json/basic-gateway/MyProxygomod/src/main.go:41 +0xa7

**Comment by skothari-tibco** [comment]
Hey, Can you update the cli and try it again? `flogo install github.com/project-flogo/microgateway@master` works for me. 

Thanks

**Comment by ykalidin** [comment]
Working fine.
