### ISSUE TITLE
Unable to install custom-pattern

### ISSUE THREAD

**Issue by ykalidin** [project-flogo/microgateway#44]
Example Recipe Link: https://github.com/project-flogo/microgateway/tree/master/examples/json/custom-pattern
Steps to produce:
1)Clone the microgateway Repository:
git clone https://github.com/project-flogo/microgateway
cd microgateway/examples/json/custom-pattern
2)Create the flogo App:
flogo create -f flogo.json
cd MyProxy
3)Try installing the custom-pattern
flogo install github.com/project-flogo/microgateway/examples/json/custom-pattern
Below error is seen:
**panic: runtime error: index out of range**

**Comment by pointlander** [comment]
fixed with latest cli

**Comment by ykalidin** [comment]
Working fine.
