### ISSUE TITLE
Error seen on using flogo build command

### ISSUE THREAD

**Issue by ykalidin** [project-flogo/microgateway#45]
Example Recipe Link: https://github.com/project-flogo/microgateway/tree/master/examples/json/basic-gateway
Steps to produce:
1)Clone the microgateway Repository:
git clone https://github.com/project-flogo/microgateway
cd microgateway/examples/json/basic-gateway
2)Create the flogo App:
flogo create -f flogo.json
cd MyProxy
3)Try the build command:
flogo build
Below error is seen:

Error in building /home/mashling/micro/src
Error: # github.com/project-flogo/flow/definition
../../go/pkg/mod/github.com/project-flogo/flow@v0.9.0-alpha.3/definition/definition_ser.go:87:52: **not enough arguments in call to mapper.ConvertLegacyMappings**
	have (*mapper.LegacyMappings)
	want (*mapper.LegacyMappings, resolve.CompositeResolver)

**Comment by pointlander** [comment]
fixed

**Comment by ykalidin** [comment]
Working fine.
