### ISSUE TITLE
Unable to run the Microgateway API examples

### ISSUE THREAD

**Issue by ykalidin** [project-flogo/microgateway#46]
Example recipe link: https://github.com/project-flogo/microgateway/tree/master/examples/api/async-gateway

Steps to reproduce:
1)Take the latest Flogo.
2)Clone the microgateway project
git clone https://github.com/project-flogo/microgateway
cd microgateway/examples/api/async-gateway
3)Run the main.go
go run main.go
Below error is seen:
github.com/project-flogo/microgateway
../../../../action.go:116:15: config.Data undefined (type *action.Config has no field or method Data)
../../../../action.go:117:31: config.Data undefined (type *action.Config has no field or method Data)

The same is observed with all API examples.

**Comment by pointlander** [comment]
fixed

**Comment by ykalidin** [comment]
Working Fine.
