### ISSUE TITLE
Exact error message is not displayed for invalid JWT token

### ISSUE THREAD

**Issue by ykalidin** [project-flogo/microgateway#8]
JWT example-Json Model:
1)Run the microgateway
2)When an invalid access token is passed in the below curl request the exact error message is not being displayed.
curl --request GET http://localhost:9096/pets -H "Authorization: Bearer <Access_Token>"
The below error is seen for all invalid JWT Access Tokens.
{"error":{"data":null,"status":405}}

**Comment by pointlander** [comment]
flogo.json was updated to use jwt output for error
