### ISSUE TITLE
No error is displayed with the attack payload in sqld

### ISSUE THREAD

**Issue by ykalidin** [project-flogo/microgateway#9]
Sqld Example -API Model
1)Run the main.go file
2)Inject the attack payload with the below command
curl http://localhost:9096/pets --upload-file attack-payload.json
No error is displayed in the Response.Below is the response:
{"category":{"id":0,"name":"string"},"id":1,"name":" or 1=1 ","photoUrls":["string"],"status":"available","tags":[{"id":0,"name":"string"}]}

**Comment by pointlander** [comment]
README was updated to use Content-Type in curl
